/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	kueuev1beta2 "sigs.k8s.io/kueue/apis/kueue/v1beta2"
)

// PreemptionConfigPriorityConstraintApplyConfiguration represents a declarative configuration of the PreemptionConfigPriorityConstraint type for use
// with apply.
//
// PreemptionConfigPriorityConstraint defines the requirements for the priority of preemption candidates.
type PreemptionConfigPriorityConstraintApplyConfiguration struct {
	// mode specifies whether priority comparison uses base or boosted (effective) priority.
	Mode *kueuev1beta2.PreemptionConfigPriorityMode `json:"mode,omitempty"`
	// comparison defines how the candidate's priority compares to the preemptor's priority.
	// For example, "LessThan" means that only workloads with lower
	// priority will be allowed as preemption candidates.
	Comparison *kueuev1beta2.NumericComparison `json:"comparison,omitempty"`
}

// PreemptionConfigPriorityConstraintApplyConfiguration constructs a declarative configuration of the PreemptionConfigPriorityConstraint type for use with
// apply.
func PreemptionConfigPriorityConstraint() *PreemptionConfigPriorityConstraintApplyConfiguration {
	return &PreemptionConfigPriorityConstraintApplyConfiguration{}
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *PreemptionConfigPriorityConstraintApplyConfiguration) WithMode(value kueuev1beta2.PreemptionConfigPriorityMode) *PreemptionConfigPriorityConstraintApplyConfiguration {
	b.Mode = &value
	return b
}

// WithComparison sets the Comparison field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Comparison field is set to the value of the last call.
func (b *PreemptionConfigPriorityConstraintApplyConfiguration) WithComparison(value kueuev1beta2.NumericComparison) *PreemptionConfigPriorityConstraintApplyConfiguration {
	b.Comparison = &value
	return b
}
