/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	kueuev1alpha1 "sigs.k8s.io/kueue/apis/kueue/v1alpha1"
	applyconfigurationkueuev1alpha1 "sigs.k8s.io/kueue/client-go/applyconfiguration/kueue/v1alpha1"
	scheme "sigs.k8s.io/kueue/client-go/clientset/versioned/scheme"
)

// PreemptionLimitsGetter has a method to return a PreemptionLimitInterface.
// A group's client should implement this interface.
type PreemptionLimitsGetter interface {
	PreemptionLimits() PreemptionLimitInterface
}

// PreemptionLimitInterface has methods to work with PreemptionLimit resources.
type PreemptionLimitInterface interface {
	Create(ctx context.Context, preemptionLimit *kueuev1alpha1.PreemptionLimit, opts v1.CreateOptions) (*kueuev1alpha1.PreemptionLimit, error)
	Update(ctx context.Context, preemptionLimit *kueuev1alpha1.PreemptionLimit, opts v1.UpdateOptions) (*kueuev1alpha1.PreemptionLimit, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, preemptionLimit *kueuev1alpha1.PreemptionLimit, opts v1.UpdateOptions) (*kueuev1alpha1.PreemptionLimit, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kueuev1alpha1.PreemptionLimit, error)
	List(ctx context.Context, opts v1.ListOptions) (*kueuev1alpha1.PreemptionLimitList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kueuev1alpha1.PreemptionLimit, err error)
	Apply(ctx context.Context, preemptionLimit *applyconfigurationkueuev1alpha1.PreemptionLimitApplyConfiguration, opts v1.ApplyOptions) (result *kueuev1alpha1.PreemptionLimit, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, preemptionLimit *applyconfigurationkueuev1alpha1.PreemptionLimitApplyConfiguration, opts v1.ApplyOptions) (result *kueuev1alpha1.PreemptionLimit, err error)
	PreemptionLimitExpansion
}

// preemptionLimits implements PreemptionLimitInterface
type preemptionLimits struct {
	*gentype.ClientWithListAndApply[*kueuev1alpha1.PreemptionLimit, *kueuev1alpha1.PreemptionLimitList, *applyconfigurationkueuev1alpha1.PreemptionLimitApplyConfiguration]
}

// newPreemptionLimits returns a PreemptionLimits
func newPreemptionLimits(c *KueueV1alpha1Client) *preemptionLimits {
	return &preemptionLimits{
		gentype.NewClientWithListAndApply[*kueuev1alpha1.PreemptionLimit, *kueuev1alpha1.PreemptionLimitList, *applyconfigurationkueuev1alpha1.PreemptionLimitApplyConfiguration](
			"preemptionlimits",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *kueuev1alpha1.PreemptionLimit { return &kueuev1alpha1.PreemptionLimit{} },
			func() *kueuev1alpha1.PreemptionLimitList { return &kueuev1alpha1.PreemptionLimitList{} },
		),
	}
}
