/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	kueuev1alpha1 "sigs.k8s.io/kueue/apis/kueue/v1alpha1"
)

// PreemptionLimitLister helps list PreemptionLimits.
// All objects returned here must be treated as read-only.
type PreemptionLimitLister interface {
	// List lists all PreemptionLimits in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kueuev1alpha1.PreemptionLimit, err error)
	// Get retrieves the PreemptionLimit from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kueuev1alpha1.PreemptionLimit, error)
	PreemptionLimitListerExpansion
}

// preemptionLimitLister implements the PreemptionLimitLister interface.
type preemptionLimitLister struct {
	listers.ResourceIndexer[*kueuev1alpha1.PreemptionLimit]
}

// NewPreemptionLimitLister returns a new PreemptionLimitLister.
func NewPreemptionLimitLister(indexer cache.Indexer) PreemptionLimitLister {
	return &preemptionLimitLister{listers.New[*kueuev1alpha1.PreemptionLimit](indexer, kueuev1alpha1.Resource("preemptionlimit"))}
}
