/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	apiskueuev1alpha1 "sigs.k8s.io/kueue/apis/kueue/v1alpha1"
	versioned "sigs.k8s.io/kueue/client-go/clientset/versioned"
	internalinterfaces "sigs.k8s.io/kueue/client-go/informers/externalversions/internalinterfaces"
	kueuev1alpha1 "sigs.k8s.io/kueue/client-go/listers/kueue/v1alpha1"
)

// PreemptionLimitInformer provides access to a shared informer and lister for
// PreemptionLimits. Prefer using the type-safe variant (see [TypedPreemptionLimitInformer]).
type PreemptionLimitInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() kueuev1alpha1.PreemptionLimitLister
}

// TypedPreemptionLimitInformer provides access to a shared informer and lister for
// PreemptionLimits, including the type-safe TypedInformer variant.
// It is a superset of PreemptionLimitInformer.
type TypedPreemptionLimitInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() PreemptionLimitIndexInformer
	Lister() kueuev1alpha1.PreemptionLimitLister
}

// PreemptionLimitIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type PreemptionLimitIndexInformer cache.TypedSharedIndexInformer[*apiskueuev1alpha1.PreemptionLimit]

// PreemptionLimitHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for PreemptionLimit.
type PreemptionLimitHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apiskueuev1alpha1.PreemptionLimit]

// PreemptionLimitDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for PreemptionLimit.
type PreemptionLimitDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apiskueuev1alpha1.PreemptionLimit]

// PreemptionLimitFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for PreemptionLimit.
type PreemptionLimitFilteringHandler = cache.TypedFilteringResourceEventHandler[*apiskueuev1alpha1.PreemptionLimit]

// PreemptionLimitIndexers is a specialization of [cache.TypedIndexers] for PreemptionLimit.
type PreemptionLimitIndexers = cache.TypedIndexers[*apiskueuev1alpha1.PreemptionLimit]

// DeletedPreemptionLimit is a specialization of [cache.DeletedObject] for PreemptionLimit.
type DeletedPreemptionLimit = cache.DeletedObject[*apiskueuev1alpha1.PreemptionLimit]

type preemptionLimitInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewPreemptionLimitInformer constructs a new informer for PreemptionLimit type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedPreemptionLimitInformer]).
func NewPreemptionLimitInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewPreemptionLimitInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedPreemptionLimitInformer constructs a new informer for PreemptionLimit type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedPreemptionLimitInformer(client versioned.Interface, resyncPeriod time.Duration, indexers PreemptionLimitIndexers) PreemptionLimitIndexInformer {
	return NewTypedPreemptionLimitInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredPreemptionLimitInformer constructs a new informer for PreemptionLimit type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredPreemptionLimitInformer]).
func NewFilteredPreemptionLimitInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedPreemptionLimitInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredPreemptionLimitInformer constructs a new informer for PreemptionLimit type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredPreemptionLimitInformer(client versioned.Interface, resyncPeriod time.Duration, indexers PreemptionLimitIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) PreemptionLimitIndexInformer {
	return NewTypedPreemptionLimitInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewPreemptionLimitInformerWithOptions constructs a new informer for PreemptionLimit type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedPreemptionLimitInformerWithOptions]).
func NewPreemptionLimitInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedPreemptionLimitInformerWithOptions(client, options)
}

// NewTypedPreemptionLimitInformerWithOptions constructs a new informer for PreemptionLimit type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedPreemptionLimitInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) PreemptionLimitIndexInformer {
	gvr := schema.GroupVersionResource{Group: "kueue.x-k8s.io", Version: "v1alpha1", Resource: "preemptionlimits"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apiskueuev1alpha1.PreemptionLimit](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.KueueV1alpha1().PreemptionLimits().List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.KueueV1alpha1().PreemptionLimits().Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.KueueV1alpha1().PreemptionLimits().List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.KueueV1alpha1().PreemptionLimits().Watch(ctx, opts)
			},
		}, client),
		&apiskueuev1alpha1.PreemptionLimit{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *preemptionLimitInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedPreemptionLimitInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *preemptionLimitInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *preemptionLimitInformer) TypedInformer() PreemptionLimitIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apiskueuev1alpha1.PreemptionLimit](f.factory.InformerFor(&apiskueuev1alpha1.PreemptionLimit{}, f.defaultInformer))
}

func (f *preemptionLimitInformer) Lister() kueuev1alpha1.PreemptionLimitLister {
	return kueuev1alpha1.NewPreemptionLimitLister(f.Informer().GetIndexer())
}

// ToTypedPreemptionLimitInformer converts an untyped informer into a TypedPreemptionLimitInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *PreemptionLimit. If that is not the case, calling type-safe methods of the returned
// TypedPreemptionLimitInformer leads to runtime panics. A safer alternative is to pass
// around a TypedPreemptionLimitInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedPreemptionLimitInformer(informer PreemptionLimitInformer) TypedPreemptionLimitInformer {
	if informer, ok := informer.(TypedPreemptionLimitInformer); ok {
		return informer
	}
	return &preemptionLimitTypedInformerAdapter{informer}
}

type preemptionLimitTypedInformerAdapter struct {
	PreemptionLimitInformer
}

func (a *preemptionLimitTypedInformerAdapter) TypedInformer() PreemptionLimitIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apiskueuev1alpha1.PreemptionLimit](a.Informer())
}

// ToPreemptionLimitIndexInformer converts an untyped informer into a PreemptionLimitIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *PreemptionLimit. If that is not the case, calling type-safe methods of the returned
// PreemptionLimitIndexInformer leads to runtime panics. A safer alternative is to pass
// around a PreemptionLimitIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToPreemptionLimitIndexInformer(informer cache.SharedIndexInformer) PreemptionLimitIndexInformer {
	if informer, ok := informer.(PreemptionLimitIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apiskueuev1alpha1.PreemptionLimit](informer)
}
