/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PreemptionLimitStatusApplyConfiguration represents a declarative configuration of the PreemptionLimitStatus type for use
// with apply.
//
// PreemptionLimitStatus defines the observed state of PreemptionLimit
type PreemptionLimitStatusApplyConfiguration struct {
	// counts is periodically updated, for reference only.
	// Restricted to the top 1000 counts to fit within CRD size limits.
	//
	Counts []PreemptionLimitCountApplyConfiguration `json:"counts,omitempty"`
}

// PreemptionLimitStatusApplyConfiguration constructs a declarative configuration of the PreemptionLimitStatus type for use with
// apply.
func PreemptionLimitStatus() *PreemptionLimitStatusApplyConfiguration {
	return &PreemptionLimitStatusApplyConfiguration{}
}

// WithCounts adds the given value to the Counts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Counts field.
func (b *PreemptionLimitStatusApplyConfiguration) WithCounts(values ...*PreemptionLimitCountApplyConfiguration) *PreemptionLimitStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithCounts")
		}
		b.Counts = append(b.Counts, *values[i])
	}
	return b
}
