/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PreemptionLimitCountApplyConfiguration represents a declarative configuration of the PreemptionLimitCount type for use
// with apply.
//
// PreemptionLimitCount tracks the number of preemptions for a single scoped entity.
type PreemptionLimitCountApplyConfiguration struct {
	// name identifies the scoped entity.
	// For Global scope it is "Global".
	// For PreemptingClusterQueue and PreemptedClusterQueue scopes it is the ClusterQueue name.
	// For PreemptedWorkload scope it is "<namespace>/<workload-name>".
	//
	Name *string `json:"name,omitempty"`
	// count is the number of preemptions recorded within the sliding time window.
	//
	Count *int32 `json:"count,omitempty"`
}

// PreemptionLimitCountApplyConfiguration constructs a declarative configuration of the PreemptionLimitCount type for use with
// apply.
func PreemptionLimitCount() *PreemptionLimitCountApplyConfiguration {
	return &PreemptionLimitCountApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PreemptionLimitCountApplyConfiguration) WithName(value string) *PreemptionLimitCountApplyConfiguration {
	b.Name = &value
	return b
}

// WithCount sets the Count field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Count field is set to the value of the last call.
func (b *PreemptionLimitCountApplyConfiguration) WithCount(value int32) *PreemptionLimitCountApplyConfiguration {
	b.Count = &value
	return b
}
