/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
	kueuev1alpha1 "sigs.k8s.io/kueue/apis/kueue/v1alpha1"
)

// PreemptionLimitSpecApplyConfiguration represents a declarative configuration of the PreemptionLimitSpec type for use
// with apply.
//
// PreemptionLimitSpec defines the desired state of PreemptionLimit
type PreemptionLimitSpecApplyConfiguration struct {
	// scope specifies the entity boundary for this preemption limit.
	//
	Scope *kueuev1alpha1.PreemptionLimitScope `json:"scope,omitempty"`
	// configSelector selects PreemptionConfigs to which this limit applies.
	// If not set, it applies to all PreemptionConfigs.
	//
	ConfigSelector *v1.LabelSelectorApplyConfiguration `json:"configSelector,omitempty"`
	// clusterQueueSelector selects ClusterQueues to which this limit applies.
	// If not set, it applies to all ClusterQueues under the configured scope.
	//
	ClusterQueueSelector *v1.LabelSelectorApplyConfiguration `json:"clusterQueueSelector,omitempty"`
	// ruleNames restricts the limit to specific rule names within matching PreemptionConfigs.
	// If not set, it applies to all rules.
	//
	RuleNames []string `json:"ruleNames,omitempty"`
	// limit defines how many preemption events can occur within the given time window.
	// An event is defined as a confirmed (preemptor, preemptee) eviction pair.
	// Setting limit to 0 blocks all preemptions under this limit's scope.
	//
	Limit *int32 `json:"limit,omitempty"`
	// limitWindowSeconds specifies the sliding time window duration, in seconds.
	// Must be greater than or equal to 1 to prevent sub-second thrashing.
	//
	LimitWindowSeconds *int32 `json:"limitWindowSeconds,omitempty"`
}

// PreemptionLimitSpecApplyConfiguration constructs a declarative configuration of the PreemptionLimitSpec type for use with
// apply.
func PreemptionLimitSpec() *PreemptionLimitSpecApplyConfiguration {
	return &PreemptionLimitSpecApplyConfiguration{}
}

// WithScope sets the Scope field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Scope field is set to the value of the last call.
func (b *PreemptionLimitSpecApplyConfiguration) WithScope(value kueuev1alpha1.PreemptionLimitScope) *PreemptionLimitSpecApplyConfiguration {
	b.Scope = &value
	return b
}

// WithConfigSelector sets the ConfigSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigSelector field is set to the value of the last call.
func (b *PreemptionLimitSpecApplyConfiguration) WithConfigSelector(value *v1.LabelSelectorApplyConfiguration) *PreemptionLimitSpecApplyConfiguration {
	b.ConfigSelector = value
	return b
}

// WithClusterQueueSelector sets the ClusterQueueSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterQueueSelector field is set to the value of the last call.
func (b *PreemptionLimitSpecApplyConfiguration) WithClusterQueueSelector(value *v1.LabelSelectorApplyConfiguration) *PreemptionLimitSpecApplyConfiguration {
	b.ClusterQueueSelector = value
	return b
}

// WithRuleNames adds the given value to the RuleNames field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RuleNames field.
func (b *PreemptionLimitSpecApplyConfiguration) WithRuleNames(values ...string) *PreemptionLimitSpecApplyConfiguration {
	for i := range values {
		b.RuleNames = append(b.RuleNames, values[i])
	}
	return b
}

// WithLimit sets the Limit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Limit field is set to the value of the last call.
func (b *PreemptionLimitSpecApplyConfiguration) WithLimit(value int32) *PreemptionLimitSpecApplyConfiguration {
	b.Limit = &value
	return b
}

// WithLimitWindowSeconds sets the LimitWindowSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LimitWindowSeconds field is set to the value of the last call.
func (b *PreemptionLimitSpecApplyConfiguration) WithLimitWindowSeconds(value int32) *PreemptionLimitSpecApplyConfiguration {
	b.LimitWindowSeconds = &value
	return b
}
